### ISSUE TITLE
关于圆桌以后升级成 journal club

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#10]
讨论：

1. 扩展圆桌内容
    增加新的项目，而不仅仅限制为讨论内容创造。就像 journal  club 一样，可以分享有趣的知识。
2. 圆桌内容记录可以在星海航纪中呈现。
    以后的的圆桌内容可以考虑总结写在星海航纪中。

**Comment by ProtossProbe** [comment]
不懂......journal club是干什么用的？

**Comment by emptymalei** [comment]
@ProtossProbe 你不好好过年……

就是一起学习知识的。比如讨论有趣的知识点/文章/视频/程序什么的。

**Comment by unionx** [comment]
圆桌内容可以写在星海航记里+1

不过还是不太清楚 journal club 的模式有什么不同

**Comment by emptymalei** [comment]
Journal Club 就是一个分享有趣的知识的小聚会吧，我主要是想说我们以后可以不仅仅局限在想要讨论设定的时候才举行，如果有人看到一个很好玩的事情，也可以分享一下。可以是一个非常简短的分享小知识，几分钟的也行，就是我们举行圆桌的时候简单的给大家解释一下。

所以一个正常的流程是：
分享知识 + 圆桌主题讨论

叫 journal club 可能有点不是那么准确，因为我们又不一定是学术的 journal 文章的分享。反正就是这个意思啦。

**Comment by unionx** [comment]
那我们可以列一个感兴趣的 topic list，看谁觉得哪个好就讲讲

**Comment by emptymalei** [comment]
@unionx 不需要啊，就是自己平时看东西看到的拿来讲讲，又不是强制去看什么东西来讲。

**Comment by styra** [comment]
赞成，感觉会很好玩。
