### ISSUE TITLE
第九次星际圆桌

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#11]
第九次星际圆桌：……

@InterImm/editors 

~~第九次讨论什么呀？下周（03 月 15 日）可以么？~~ 那就定在下周（03 月 15 日）

我们现在还在进行中的事情：

1. 公司列表
2. 太阳系旅行指南
3. [所谓的资格考试题目](https://github.com/InterImm/InterImmBook/issues/71) 我发现我不知道题目如何出是好
4. [时间线](https://github.com/InterImm/InterImmBook/issues/17)

时间：03月14日，周六，早上10点
形式：Skype 讨论。
时长：预计一到三小时。

-----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by ProtossProbe** [comment]
额，这周日有个考试要参加......下周举办行么？

**Comment by emptymalei** [comment]
@ProtossProbe 好呀。

考试顺利啊。

**Comment by styra** [comment]
我都可以的。
开学就有考试啊，祝顺利～

**Comment by unionx** [comment]
不如继续聊旅游啊哈哈哈

**Comment by emptymalei** [comment]
提醒，周六早上哦。

**Comment by emptymalei** [comment]
**时间 2039 年**

* 参与公司：
太空制造公司 － 美国
中国航天集团 － 中国
ESA － 欧洲
NASA － 美国

* 开发历程：
2013 年，嫦娥三号和玉兔号月球车在月球表面着陆；
2017 年，嫦娥五号和玉兔二号月球车在月球表面着陆；
2026 年，中国航天局与 ESA 合作，在月球表面使用 3D 打印设备，利用月壤建立了一个试验性的居住点；
2029 年，在第一个居住点旁边，第二个永久居住点建立，并且安装上了完整的维生设备；
2030 年，第一批宇航员在居住点登陆，并居住生活舱中。20 天后返回地球；
2032 年，第一个月球科研基地在居住点旁边建成，主要进行月球资源勘探、地外天文观测、行星科学、引力波探测等科学研究，中国和欧洲长期派驻人员；
2039 年，中国航天集团开始在月球虹湾建立首个资源开采基地，主要开采钛铁矿；
2040 年，近地小行星矿业公司在风暴洋建立了稀土资源和铁矿开采基地。
2041 年，中国航天集团和近地小行星矿业公司都与太空制造公司建立了合作关系。
2042 年，中国航天集团开始在月球建立首个旅游中心；
