### ISSUE TITLE
第十次星际圆桌：系外行星及其他设定讨论

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#13]
第十次星际圆桌的话题是：系外行星

时间：04月04日，周六，早上10点
形式：Skype 讨论。
时长：N小时。

**这个时间可以么？**

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by ProtossProbe** [comment]
没问题。刚好这周没实验......

**Comment by unionx** [comment]
可以可以~

**Comment by emptymalei** [comment]
@styra 可以给我们讲讲上次系外行星的东西么？

**Comment by emptymalei** [comment]
推迟一周可以么？

**Comment by styra** [comment]
抱歉大家，没有及时回复哈。
这周事情比较多，周末要赶活，推迟一周大家方便吗？
