### ISSUE TITLE
第十一次星际圆桌：系外行星和火星地球化

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#14]
这个什么时间合适呢？

--------

第十一次星际圆桌的话题是：系外行星和火星地球化

时间：待定，周六，早上10点
形式：Skype 讨论。
时长：N小时。

**这个时间可以么？**

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by styra** [comment]
这周可以啊。
我们可以讨论下我上次听的关于系外行星的报告，主要是关于宜居带和M型矮星的。

**Comment by emptymalei** [comment]
@styra 这周 @ProtossProbe 好像没时间。来看看大家有没有时间吧。

* 这周
- [ ] 周六（04-11）
- [ ] 周日（04-12）
* 下周
- [ ] 周六（04-18）
- [ ] 周日（04-19）

**Comment by ProtossProbe** [comment]
理论上我这周和下周都没有时间.......

**Comment by emptymalei** [comment]
@ProtossProbe 其实我这几周也会挺忙的，因为是期末了。我们再往后延期看看吧。

**Comment by styra** [comment]
@emptymalei 好的。

**Comment by ProtossProbe** [comment]
这周周六？

**Comment by emptymalei** [comment]
我可以。

**Comment by styra** [comment]
不知道skype上的消息发出去没有。这周末有事参加不了啊。

在 2015-04-22 01:42:31，OctoMiao <notifications@github.com> 写道：


我可以。

**Comment by emptymalei** [comment]
总结：
https://docs.google.com/document/d/1u805FFN3uDq9nfY1IASDuM3dsS2AlSuHrLKn47YNKWU/edit?usp=sharing

**Comment by unionx** [comment]
主页上第十二次的链接跳到这里了......

**Comment by emptymalei** [comment]
@unionx 啊，搞错了，刚刚改好了。
