### ISSUE TITLE
第十二次星际圆桌：系外行星和宜居带

### ISSUE THREAD

**Issue by styra** [InterImm/roundTable#15]
第十二次星际圆桌的话题是：系外行星和宜居带

时间：2015-06-13，周六，早上10点
形式：Skype 讨论。
时长：N小时。

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by styra** [comment]
我下周末到下下周末（16-24）都在外地开会。
所以我5月只有这周末和5月30号的最后一个周末能参加了。
大家什么时候方便呢？

**Comment by emptymalei** [comment]
@styra 我这周不行哎，需要准备回家的事情，有很多事情需要整理好。我们五月底？

**Comment by styra** [comment]
好啊。

**Comment by ProtossProbe** [comment]
五月底可以

**Comment by emptymalei** [comment]
五月30号下午行么？我上午可能一直在火车上。

**Comment by ProtossProbe** [comment]
下午几点呢？

**Comment by emptymalei** [comment]
下午两点开始？

**Comment by ProtossProbe** [comment]
我没问题.......

**Comment by ProtossProbe** [comment]
突然想起来那时候有课……星期天下午可以么？

**Comment by emptymalei** [comment]
啊，星期天下午我在火车上呢。

**Comment by ProtossProbe** [comment]
那还有什么时间？我这周有空的是周五晚上，周六早上和周日下午

**Comment by styra** [comment]
我都行。

**Comment by unionx** [comment]
周一吧周一吧~~

**Comment by emptymalei** [comment]
整个下周我都在外转悠哎

**Comment by ProtossProbe** [comment]
下一次圆桌什么时候开啊╮(￣▽￣)╭

**Comment by styra** [comment]
╮(￣▽￣)╭

**Comment by unionx** [comment]
只能周末吧 ╮(￣▽￣)╭

**Comment by emptymalei** [comment]
这周六？

**Comment by ProtossProbe** [comment]
我没问题。

**Comment by unionx** [comment]
吼！

**Comment by emptymalei** [comment]
@styra 你呢？

**Comment by emptymalei** [comment]
主要听 @styra 讲了田丰在上台做的系外行星宜居带的讲座。关于 M dwarf 的。
