### ISSUE TITLE
第十三次星际圆桌：太空电梯以及运营事项

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#16]
~~话题继续讨论太空电梯？~~

讨论太空电梯以及运营事项

-----

时间：周六（7月18日），早上10点
形式：Skype 讨论。
时长：N小时。

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by ProtossProbe** [comment]
我这边时差12小时...

**Comment by emptymalei** [comment]
-----
我们俩倒是差不多。

所以现在安排下来的集智俱乐部的日程是July 24 9pm MDT，你要专门将一下你的一些想法或者现在的工作么？你没有想要讲的话再轮到我，因为我觉得我对太空技术什么并不是那么了解。

http://computational-communication.com/post/guan-yu-wo-men/2015-05-09-anual-symposium?from=timeline&isappinstalled=0

**Comment by ProtossProbe** [comment]
还是你讲吧......那个时候我这里都深夜了，而且看起来好正式

**Comment by ProtossProbe** [comment]
我局的讲座在一堆大数据中间，看起来瞬间高大上了不少😂

**Comment by emptymalei** [comment]
== 我讲只能大概的讲讲了，细节什么也讲不了。其实主要做广告吧。

**Comment by styra** [comment]
赞～
时间没问题～

**Comment by styra** [comment]
感觉灰常高大上～

**Comment by emptymalei** [comment]
好那就定在周六（7月18日）早上十点

**Comment by emptymalei** [comment]
总结：
1. 讨论了太空电梯的横截面函数
2. 讨论太空电梯上的振动模式
3. 火星日历/历法复习
4. 运营微博事项
