### ISSUE TITLE
第十四次星际圆桌：星际移民之书设定的讨论

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#17]
第十四次星际圆桌的话题是：~~系外行星和宜居带~~ 星际移民之书设定的讨论

时间：2015-08-08，周六，早上9点
形式：Skype 讨论。
时长：N小时。

可以进行的内容：

1. ~~太空电梯继续：https://github.com/InterImm/InterImmBook/issues/78~~
2. ~~我想我们可以大家一起来讨论几篇文章（有的我看过了，可以大致跟大家说一下内容，嗯嗯这就是我之前说的 journal club 的形式，大家来讨论一些文章什么的，虽然以前也这么做……）：~~
   1. ~~[Observational Signatures of Self-Destructive Civilisations](http://arxiv.org/abs/1507.08530)~~
   2. ~~[Earth Similarity Index with two free parameters](http://arxiv.org/abs/1507.06293)~~
   3. ~~[Statistical Signatures of Panspermia in Exoplanet Surveys](http://arxiv.org/abs/1507.05614)~~
   4. ~~[Should we geoengineer larger ice caps?](http://arxiv.org/abs/1507.05495)~~
   5. ~~[Interview with John Bucknell about his Airbreathing nuclear thermal rocket design](http://nextbigfuture.com/2015/07/interview-with-john-bucknell-about-his.html): from nextbigfuture 这上面的文章经常很水或者很偏激，不过这篇采访应该还好。~~
3. 《星际移民之书》继续设定

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by ProtossProbe** [comment]
嗯？怎么还是讨论系外行星？另外日期不对吧。？

**Comment by emptymalei** [comment]
@ProtossProbe 不知道最近讨论什么好，所以列举一下，看看大家对什么感兴趣呢？

日期OTL，我竟然写上了今天的日期……

**Comment by emptymalei** [comment]
@ProtossProbe @unionx 舟没有时间，你们俩要来讨论设定么？

**Comment by ProtossProbe** [comment]
我有时间。

**Comment by ProtossProbe** [comment]
要不可以提前一个或者半个小时？？

**Comment by emptymalei** [comment]
好我们可以提前一小时

**Comment by emptymalei** [comment]
来协调一下设定吧，昨天讨论的内容：

1. 电梯是火星建设的，地球没有。
2. 太空电梯在火星地球化之前就建好了一台，时间在一些城市圈建设成功之后但是火星地球化之前，可以选择 2160 年左右，这时候城市圈几个建成了几个在建设，运输方面大家觉得需要更多地投入。在火星地球化开始的阶段建设了另外两架，时间可以设定在 2215 年（2213年星际移民局第一次尝试呼吁地球协助火星进行地球化工作，2216年第二次呼吁，设定在 2215年可以作为一个筹码，像地球展示自己决心之类的）和 2223 年，这时候火星地球化刚刚开始几年，电梯被视作长远来看比较优秀的投资。
3. 另外可以在 2230 年左右设定一下另外的两架电梯的建设，甚至可以同时开工。
4. 第一架在子午线城市圈附近建立，2158-2163年五年时间建立，第二架 伊希地城市圈附近，2214 -2217 三年，第三架在亚马逊城市圈附近 2223- 2225年两年。另外在 2230-2234 年期间建造两架，分别在伊希地城市圈和子午线城市圈之间，以及在伊希地城市圈和亚马逊城市圈之间。



另外想到，太阳系外围的开发应该是在火星地球化之前因为要使用太阳系外围的资源。

另外我想火星可以设立一个节日，庆祝每次火星地球化的飞船飞到火星的日子？不过如果是大型货物运输不知道是不是应该设定为使用霍曼转移轨道，如果这样的话，应该不是火星土星最近的地方。（有个时刻表但是没有火星到土星系统 http://clowder.net/hop/railroad/sched.html ）

**Comment by emptymalei** [comment]
另外关于辐射的一些内容放在了这里：

https://github.com/InterImm/InterImmBook/issues/83
