### ISSUE TITLE
第十五次星际圆桌：《星际移民之书》继续设定

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#18]
第十五次星际圆桌的话题是： 星际移民之书设定的讨论

时间：2015-09-12，周六，早上9点
形式：Skype 讨论。

可以进行的内容：

1. 《星际移民之书》继续设定

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by ProtossProbe** [comment]
好的。

**Comment by styra** [comment]
好的～

**Comment by emptymalei** [comment]
总结：

关于外太阳系开发的表格：

https://docs.google.com/spreadsheets/d/1KdyJb26RZJZpflSMGbBnZyNjn9WiY5Fhtx-tt8hysG8/edit?usp=sharing
