### ISSUE TITLE
第十六次星际圆桌：话题待定

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#19]
第十六次星际圆桌的话题待定

时间：2015-10-03，周六，早上9点
形式：Skype 讨论。

可以进行的内容：

1. 《星际移民之书》继续设定
2. 一起讨论一下热门电影？

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by styra** [comment]
@emptymalei @ProtossProbe 今天你俩讨论了吗？

**Comment by emptymalei** [comment]
@styra 只是简单讨论了一下。
