### ISSUE TITLE
第十六次星际圆桌：补充会议

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#20]
第十六次星际圆桌的补充

时间：2015-10-10，周六，早上9点
形式：Skype 讨论。

可以进行的内容：

1. 《星际移民之书》继续设定
2. 运营讨论/知乎专栏讨论

----

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

-----

* 主线
* 科普
* 火星旅游指南类似
*

**Comment by styra** [comment]
啊，明天国内是工作日……

**Comment by unionx** [comment]
今天是工作日+1

说起来我在看星海航纪的文，发觉有的设定挺有趣啊，可以拓展一下子
