### ISSUE TITLE
第十七次星际圆桌：接下来的设定和科普

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#22]
**我觉得还是北京时间周日开比较好。**

---

![](https://img.shields.io/badge/星际圆桌-第17期-green.svg?style=flat-square)

第十七次星际圆桌的话题：
1. 接下来的计划
2. 设定：继续丰富/修订星际移民之书，还是开始更遥远的未来。
3. 知乎专栏相关讨论
4. 可以讨论一些科学问题
5. 现在我们是不是应该用知乎专栏代替现在的星海航纪链接么？然后现在的星海航纪是不是要重新定位一下？
6. 一起读一下星际移民之书，看看有什么地方有问题。

时间：2015-11-08，**周日**，早上 9:30
形式：Skype 讨论。

---

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by unionx** [comment]
我对星海航纪的那几篇小说的设定挺感兴趣的哈哈哈哈

**Comment by emptymalei** [comment]
总结：https://github.com/InterImm/InterImmBook/issues/97
