### ISSUE TITLE
下次把 EasyNight 的作者也叫来参加圆桌会议吧！

### ISSUE THREAD

**Issue by unionx** [InterImm/roundTable#23]
就是这个你们晓得的：http://weibo.com/u/5456131713?topnav=1&wvr=6&topsug=1

**Comment by emptymalei** [comment]
好啊，不知道讨论什么好。

**Comment by unionx** [comment]
em......三年过去了，这个事可以安排一下

**Comment by emptymalei** [comment]
@unionx 不是已经来过了么
