### ISSUE TITLE
第十八次星际圆桌：火星救援专题

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#24]
![](https://img.shields.io/badge/星际圆桌-第18期-green.svg?style=flat-square)

第十八次星际圆桌的话题：
1. 《火星救援》相关讨论
2. 系外行星二十年历程学习
3. 火星房地产（哈哈哈帝老师起的名字）Marspolar，不过我觉得这个组织有些欺骗的性质。

时间：2015-11-29，**周日**，早上 9:30
形式：Skype/QQ群语音 讨论。

---

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by exoplanet5** [comment]
期待参加！

**Comment by emptymalei** [comment]
@physics5mickey 欢迎欢迎。

**Comment by unionx** [comment]
啊！火星救援我还没看呢

**Comment by emptymalei** [comment]
@unionx 剧透部分帝老师捂住耳朵。:tiger:
