### ISSUE TITLE
第七次圆桌讨论：行星际通信及其他

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#8]
第七次星际圆桌的话题是：行星际通信，空间站及其他

有可能主要话题转移到其他的方面，例如空间站的问题等等。

时间：01月03日，周六，早上10点
形式：Skype 讨论。
时长：预计一到三小时。

其他可以讨论的话题库[在此](https://github.com/InterImm/roundTable/issues/4)。

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by styra** [comment]
收到通知，明天见
