### ISSUE TITLE
第八次圆桌讨论

### ISSUE THREAD

**Issue by emptymalei** [InterImm/roundTable#9]
第八次星际圆桌的话题是：小行星采矿及~~（可能的）万有青年计划~~

时间：02月01日，周日，早上10点
形式：Skype 讨论。
时长：预计一到三小时。

其他可以讨论的话题库[在此](https://github.com/InterImm/roundTable/issues/4)。

过往圆桌索引：

[星际圆桌讨论话题库及过往索引](https://github.com/InterImm/roundTable/issues/4)

**Comment by ProtossProbe** [comment]
空间站的问题不是讨论过了么......对了，万有青年计划结果也该公布了吧，要不讨论具体实施的方案？？

**Comment by emptymalei** [comment]
@ProtossProbe 我从前面一次复制过来的，忘记删掉这个了。

**Comment by unionx** [comment]
不如讨论一下万青的计划啦

**Comment by emptymalei** [comment]
也好，不过需要看结果才能知道怎么讨论。

**Comment by emptymalei** [comment]
【更新了时间和话题】

我忘记把时间确定下来了。那我们定在下周吧，再加上这周万有的结果还没出。

**Comment by qnzi** [comment]
大家好啊，我是新来的。对星际移民极其感兴趣，希望可以参与到你们的讨论中间来。不知道过去的圆桌讨论还可以回复吗？会有deadline吗？

**Comment by styra** [comment]
@qnzi 欢迎啊。可以回复的，也可以发起新的issue。

**Comment by emptymalei** [comment]
@qnzi 把你的 Skype ID 告诉我吧，发到 octomiao@interimm.org 就行。我会加你好友，所以最好周五下午之前来确认一下好友，然后我才能把你拉进我们的讨论组。

**Comment by emptymalei** [comment]
总结：

1. 一起学习了小行星采矿的知识；
2. 讨论了目录结构：
   ![structure](https://cloud.githubusercontent.com/assets/663798/5991570/f151c792-a9b4-11e4-90ef-a405e9ff2824.png)

   a. 导览
   b. 历史
   c. 行业
   d. 科技
   e. 指南
